# Generated by Django 5.0.4 on 2024-09-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("functions", "0002_alter_content_author_alter_content_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="ภาพประกอบ"
            ),
        ),
    ]
