# Generated by Django 5.0.4 on 2024-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("functions", "0003_alter_content_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="youtube_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="ลิงก์ YouTube"
            ),
        ),
    ]
